import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, Clock3, Cpu, Crown, Database, FolderOpen, Globe2, HardDrive, History, MessageSquare, MonitorCog, Network, Server, Settings, X, Zap } from "lucide-react";
import "./index.css";
import { ChatPage, FilesPage, HistoryPage, NodesPage, ProcessesPage } from "./Workspaces";

type Data = Record<string, any>;
type Page = "dashboard" | "nodes" | "chat" | "files" | "processes" | "history";
type Sample = { down: number; up: number };
const THEMES = [["nightmare","Nightmare Red"],["cachyos","CachyOS Cyan"],["cyber","Cyber Neon"],["oled","Dark Matter OLED"],["light","Clean Light"],["matrix","Matrix Hacker"],["dracula","Dracula"],["nordic","Nordic Frost"],["amber","Retro Amber"]];
const NAV: {id:Page;label:string;icon:React.ReactNode;badge?:string}[] = [
  {id:"dashboard",label:"Dashboard",icon:<Activity size={15}/>},
  {id:"nodes",label:"Multi-PC Hub",icon:<Globe2 size={15}/>,badge:"Local"},
  {id:"chat",label:"Chat & Prompts",icon:<MessageSquare size={15}/>,badge:"P2P"},
  {id:"files",label:"Dateibrowser",icon:<FolderOpen size={15}/>},
  {id:"processes",label:"Prozesse",icon:<Cpu size={15}/>},
  {id:"history",label:"Historie (DuckDB)",icon:<History size={15}/>,badge:"24h"},
];
const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:0;

function Dial({label,value,tone}:{label:string;value:number;tone:string}){
  const safe=Math.max(0,Math.min(100,value));
  return <div className={`dial ${tone}`}><svg viewBox="0 0 120 120" role="img" aria-label={`${label}: ${safe.toFixed(1)} Prozent`}><circle className="track" cx="60" cy="60" r="46" fill="none" strokeWidth="8"/><circle className="arc" cx="60" cy="60" r="46" fill="none" strokeWidth="8" strokeLinecap="round" strokeDasharray="289" strokeDashoffset={289*(1-safe/100)}/></svg><div><strong>{safe.toFixed(1)}%</strong><span>{label}</span></div></div>;
}
function Meter({value,tone="cyan"}:{value:number;tone?:string}){return <div className="meter"><i className={tone} style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
function Panel({title,icon,tag,children,className=""}:{title:string;icon:React.ReactNode;tag?:string;children:React.ReactNode;className?:string}){return <section className={`panel ${className}`}><header><h2>{icon}{title}</h2>{tag&&<b>{tag}</b>}</header>{children}</section>}
function NetGraph({samples}:{samples:Sample[]}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const c=ref.current;if(!c)return;const d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*d;c.height=h*d;const x=c.getContext("2d");if(!x)return;x.scale(d,d);x.clearRect(0,0,w,h);x.strokeStyle="rgba(255,255,255,.06)";for(let r=1;r<4;r++){x.beginPath();x.moveTo(0,h*r/4);x.lineTo(w,h*r/4);x.stroke()}const max=Math.max(1,...samples.flatMap(s=>[s.down,s.up]));(["down","up"] as const).forEach((key,k)=>{const color=k?"#ffb000":"#ff304f";x.beginPath();x.strokeStyle=color;x.shadowColor=color;x.shadowBlur=7;x.lineWidth=2;samples.forEach((s,i)=>{const px=i*w/Math.max(samples.length-1,1),py=h-s[key]/max*(h-10)-5;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.shadowBlur=0})},[samples]);return <canvas ref={ref}/>;
}

function Dashboard({m,samples}:{m:Data;samples:Sample[]}){
  const cpu=m.cpu||{},ram=m.memory||{},swap=m.swap||{},gpu=m.gpus?.[0]||{},net=m.network||{},disks=m.disks||[];
  const down=n(net.download_mbps),up=n(net.upload_mbps);
  return <><div className="metrics-grid">
    <Panel title="CPU Metrics" icon={<Cpu size={14}/>} tag={cpu.model||"Processor"}><Dial label="CPU Load" value={n(cpu.percent)} tone="red"/><p className="sensor-note">{cpu.temperature_c?`${cpu.temperature_c}°C`:"Sensor n/a"} • {cpu.frequency_mhz?`${cpu.frequency_mhz} MHz`:"Takt n/a"}</p><div className="rule"/><div className="labels"><span>{cpu.logical_cores||0} Logical Cores</span><span>Per-Core Load</span></div><div className="cores">{(cpu.per_core||[0,0,0,0]).slice(0,8).map((v:number,i:number)=><span key={i}><i style={{height:`${Math.max(5,v)}%`}}/></span>)}</div></Panel>
    <Panel title="Memory / DDR" icon={<Activity size={14}/>} tag={`${n(ram.total_gb).toFixed(1)} GB Total`}><Dial label="RAM Usage" value={n(ram.percent)} tone="blue"/><p className="sensor-note">{n(ram.used_gb).toFixed(1)} GB / {n(ram.total_gb).toFixed(1)} GB</p><div className="rule"/><div className="barline"><span>Physical RAM</span><b>{n(ram.percent).toFixed(0)}%</b></div><Meter value={n(ram.percent)} tone="blue"/><div className="barline"><span>Swap / Pagefile</span><b>{n(swap.percent).toFixed(0)}%</b></div><Meter value={n(swap.percent)} tone="purple"/></Panel>
    <Panel title="GPU Accelerator" icon={<MonitorCog size={14}/>} tag={gpu.name||"Unavailable"}><Dial label="GPU Load" value={n(gpu.percent)} tone="purple"/><p className="sensor-note">{gpu.temperature_c?`${gpu.temperature_c}°C`:"Sensor n/a"} • {gpu.power_w?`${gpu.power_w}W TGP`:"Power n/a"}</p><div className="rule"/><div className="barline"><span>VRAM Speicher</span><b>{n(gpu.vram_percent).toFixed(0)}%</b></div><Meter value={n(gpu.vram_percent)} tone="purple"/><div className="labels"><span>GPU Compute</span><span>{gpu.fan_rpm||0} RPM Fans</span></div></Panel>
    <Panel title="Network I/O" icon={<Network size={14}/>} tag="LAN AUTO"><div className="rate"><div><span>↓ RX</span><b>{down.toFixed(1)} M</b></div><div><span>↑ TX</span><b>{up.toFixed(1)} M</b></div></div><div className="chart"><div><span>● RX {down.toFixed(1)}</span><span>● TX {up.toFixed(1)}</span><b>60s LIVE</b></div><NetGraph samples={samples}/></div><div className="labels"><span>Buffers: 0% loss</span><span>NIC: {net.interface||"Auto"}</span></div></Panel>
  </div><Panel title="Storage Matrix & individuelle SSD Geschwindigkeiten" icon={<HardDrive size={15}/>} className="storage"><div className="storage-top"><span>Echtzeit Lese- & Schreibraten für jedes verbundene Laufwerk</span><div><b>Total Read: {down.toFixed(1)} MB/s</b><b>Total Write: {up.toFixed(1)} MB/s</b></div></div><div className="drives">{disks.length?disks.map((d:Data)=><article key={`${d.name}-${d.mount}`}><h3><span><HardDrive size={13}/>{d.mount||d.name}</span><b>{n(d.percent).toFixed(0)}%</b></h3><small>{d.name} • {d.fstype||"Disk"}</small><Meter value={n(d.percent)}/><div className="capacity"><span>{n(d.used_gb).toFixed(0)} GB used</span><span>{Math.max(0,n(d.total_gb)-n(d.used_gb)).toFixed(0)} GB free</span></div><div className="disk-rate"><div><span>↓ Read</span><b>{n(d.read_mbps).toFixed(1)} <small>MB/s</small></b></div><div><span>↑ Write</span><b>{n(d.write_mbps).toFixed(1)} <small>MB/s</small></b></div></div></article>):<p className="empty">Keine Laufwerke verfügbar</p>}</div></Panel></>;
}

function App(){
  const initialTheme=localStorage.getItem("ncc-layout-version")==="2"?(localStorage.getItem("ncc-theme")||"nightmare"):"nightmare";
  const [snap,setSnap]=useState<Data>({metrics:{}}),[online,setOnline]=useState(false),[samples,setSamples]=useState<Sample[]>([]),[page,setPage]=useState<Page>("dashboard"),[modal,setModal]=useState<"settings"|"changelog"|null>(null),[theme,setTheme]=useState(initialTheme),[token,setToken]=useState(localStorage.getItem("ncc-token")||""),[change,setChange]=useState(""),[nodes,setNodes]=useState<Data[]>([]),[mode,setMode]=useState("local"),[clock,setClock]=useState(new Date()),[error,setError]=useState("");
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("ncc-theme",theme);localStorage.setItem("ncc-layout-version","2")},[theme]);
  useEffect(()=>{const t=setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(t)},[]);
  useEffect(()=>{let ws:WebSocket|undefined,t=0,closed=false,delay=1000,last:{s:number;r:number;t:number}|null=null;const connect=()=>{ws=new WebSocket(`${location.protocol==="https:"?"wss":"ws"}://${location.host}/ws/live?token=${encodeURIComponent(token)}`);ws.onopen=()=>{setOnline(true);delay=1000};ws.onmessage=e=>{const next=JSON.parse(e.data),net=next.metrics?.network||{},now=Date.now();let down=n(net.download_mbps),up=n(net.upload_mbps);if(!down&&!up&&last){const sec=Math.max((now-last.t)/1000,.2);down=Math.max(0,(n(net.bytes_recv)-last.r)*8/sec/1e6);up=Math.max(0,(n(net.bytes_sent)-last.s)*8/sec/1e6);next.metrics.network.download_mbps=down;next.metrics.network.upload_mbps=up}last={s:n(net.bytes_sent),r:n(net.bytes_recv),t:now};setSnap(next);setSamples(v=>[...v.slice(-59),{down,up}])};ws.onclose=()=>{setOnline(false);if(!closed){t=window.setTimeout(connect,delay);delay=Math.min(delay*2,30000)}};ws.onerror=()=>setError("Live-Verbindung unterbrochen – Reconnect läuft.")};connect();return()=>{closed=true;clearTimeout(t);ws?.close()}},[token]);
  useEffect(()=>{fetch("/api/nodes").then(r=>r.json()).then(setNodes).catch(()=>undefined);fetch("/api/multipc/mode").then(r=>r.json()).then(v=>setMode(v.mode)).catch(()=>undefined)},[snap.timestamp]);
  const m=snap.metrics||{},cpu=m.cpu||{},ram=m.memory||{},gpu=m.gpus?.[0]||{},host=m.system?.hostname||snap.node_id||"NCC NODE";
  const changelog=()=>{fetch("/api/changelog").then(r=>r.json()).then(v=>setChange(v.markdown||"")).catch(()=>setChange("Changelog konnte nicht geladen werden."));setModal("changelog")};
  const saveToken=(v:string)=>{localStorage.setItem("ncc-token",v);setToken(v)};
  const notify=(v:string)=>{setError(v);window.setTimeout(()=>setError(""),4500)};
  return <div className="app"><header className="topbar"><div className="brand"><div><Crown size={20}/></div><section><strong>no<span>0</span>bz</strong><small>◆ Nightmare <i>v0.2.0</i></small></section></div><div className="system"><b>● {online?"LIVE MODUS":"BACKEND GETRENNT"}</b><span>• WEB: 8350</span><span>• REMOTE: 8351</span></div><div className="host"><Server size={13}/><b>{host}</b><span>| {mode.toUpperCase()}</span></div><div className="clock"><Clock3 size={13}/>{clock.toLocaleTimeString("de-DE")}</div><div className="top-actions"><button onClick={()=>setPage("nodes")}><Globe2 size={13}/> {mode}</button><button onClick={changelog}><Database size={13}/> Changelog</button><button className="hot" onClick={()=>setTheme("nightmare")}><Zap size={13}/> Nightmare</button><button onClick={()=>setModal("settings")}><Crown size={13}/> Commander</button></div></header>
  <aside><label>Hauptmenü</label><nav>{NAV.map(x=><button key={x.id} className={page===x.id?"active":""} onClick={()=>setPage(x.id)}>{x.icon}<span>{x.label}</span>{x.badge&&<b>{x.badge}</b>}</button>)}<button onClick={()=>setModal("settings")}><Settings size={15}/><span>Einstellungen</span></button></nav><div className="quick"><header><span>Quick Stats</span><b>{online?"Online":"Offline"}</b></header><dl><dt>CPU Last:</dt><dd>{n(cpu.percent).toFixed(1)}%</dd><dt>GPU Last:</dt><dd>{n(gpu.percent).toFixed(1)}%</dd><dt>RAM Belegt:</dt><dd>{n(ram.used_gb).toFixed(1)} GB</dd><dt>Disks Read:</dt><dd>{n(m.network?.download_mbps).toFixed(1)} MB/s</dd></dl></div><footer><b>no0bz Command Center</b><span>// MORE FPS + MORE POWER //</span></footer></aside>
  <main>{page==="dashboard"?<Dashboard m={m} samples={samples}/>:page==="nodes"?<NodesPage nodes={nodes} mode={mode}/>:page==="chat"?<ChatPage token={token} notify={notify}/>:page==="files"?<FilesPage token={token} notify={notify}/>:page==="processes"?<ProcessesPage items={m.processes||[]} token={token} notify={notify}/>:<HistoryPage notify={notify}/>}</main><div className="statusbar"><b>no0bz COMMAND CENTER</b><span>|</span><a>v0.2.0</a><span>|</span><em>// {theme.toUpperCase()} MODE</em><div>RAM: {n(ram.used_gb).toFixed(1)} / {n(ram.total_gb).toFixed(1)} GB • <b>// NO LIMITS //</b></div></div>
  {modal&&<div className="modalback" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><div className="modal"><header><h2>{modal==="settings"?"Systemeinstellungen":"Changelog"}</h2><button onClick={()=>setModal(null)}><X size={17}/></button></header>{modal==="settings"?<div className="form"><label>Theme<select value={theme} onChange={e=>setTheme(e.target.value)}>{THEMES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>NCC Token<input value={token} onChange={e=>saveToken(e.target.value)} type="password"/></label><p>Theme und Token werden ausschließlich lokal gespeichert.</p></div>:<pre>{change}</pre>}</div></div>}{error&&<button className="toast" onClick={()=>setError("")}>{error}</button>}</div>;
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
