import React, { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, Cpu, Database, HardDrive, MessageSquare, MonitorCog, Network, Settings, Users, X } from "lucide-react";
import "./index.css";

type AnyMap = Record<string, any>;
const THEMES = [["cachyos","CachyOS Cyan"],["cyber","Cyber Neon"],["oled","Dark Matter OLED"],["light","Clean Light"],["matrix","Matrix Hacker"],["dracula","Dracula"],["nordic","Nordic Frost"],["amber","Retro Amber"],["nightmare","Nightmare Red"]];

function Gauge({ label, value }: {label:string;value:number}) {
  const safe = Math.max(0, Math.min(100, value || 0));
  return <div className="gauge-row"><svg className="gauge" viewBox="0 0 120 120" role="img" aria-label={`${label}: ${safe.toFixed(0)} Prozent`}><circle className="gauge-bg" cx="60" cy="60" r="48" fill="none" strokeWidth="9"/><circle className="gauge-value" cx="60" cy="60" r="48" fill="none" strokeWidth="9" strokeLinecap="round" strokeDasharray="301.6" strokeDashoffset={301.6*(1-safe/100)}/></svg><div><div className="value">{safe.toFixed(0)}<span className="unit">%</span></div><div className="muted">{label}</div></div></div>;
}

function NetworkGraph({ samples }: {samples:{down:number;up:number}[]}) {
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{let frame=0;const draw=()=>{const c=ref.current;if(!c)return;const dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext("2d");if(!x)return;x.scale(dpr,dpr);x.clearRect(0,0,w,h);const max=Math.max(1,...samples.flatMap(s=>[s.down,s.up]));([["down","#12d8f4"],["up","#ffb02e"]] as const).forEach(([key,color])=>{x.beginPath();x.strokeStyle=color;x.lineWidth=2;samples.forEach((s,i)=>{const px=i*Math.max(1,w/(samples.length-1));const py=h-(s[key]/max)*(h-10)-5;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()});frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame)},[samples]);return <canvas ref={ref} aria-label="Netzwerkverlauf: Download cyan, Upload amber"/>;
}

function Card({title,icon,wide=false,children}:{title:string;icon:React.ReactNode;wide?:boolean;children:React.ReactNode}){return <section className={`card ${wide?"wide":""}`}><div className="cardhead"><div className="cardtitle">{title}</div>{icon}</div>{children}</section>}

function App(){
  const [snapshot,setSnapshot]=useState<AnyMap>({metrics:{}}),[connected,setConnected]=useState(false),[samples,setSamples]=useState<{down:number;up:number}[]>([]),[modal,setModal]=useState<"settings"|"changelog"|null>(null),[theme,setTheme]=useState(localStorage.getItem("ncc-theme")||"cachyos"),[token,setToken]=useState(localStorage.getItem("ncc-token")||""),[change,setChange]=useState(""),[nodes,setNodes]=useState<AnyMap[]>([]),[error,setError]=useState("");
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("ncc-theme",theme)},[theme]);
  useEffect(()=>{let socket:WebSocket|undefined,timer=0,closed=false,delay=1000;const connect=()=>{const scheme=location.protocol==="https:"?"wss":"ws";socket=new WebSocket(`${scheme}://${location.host}/ws/live?token=${encodeURIComponent(token)}`);socket.onopen=()=>{setConnected(true);delay=1000};socket.onmessage=e=>{const next=JSON.parse(e.data);setSnapshot(next);const n=next.metrics?.network||{};setSamples(old=>[...old.slice(-59),{down:n.download_mbps||0,up:n.upload_mbps||0}])};socket.onclose=()=>{setConnected(false);if(!closed){timer=window.setTimeout(connect,delay);delay=Math.min(delay*2,30000)}};socket.onerror=()=>setError("Live-Verbindung unterbrochen – neuer Versuch läuft.")};connect();return()=>{closed=true;clearTimeout(timer);socket?.close()}},[token]);
  useEffect(()=>{fetch("/api/nodes").then(r=>r.json()).then(setNodes).catch(()=>undefined)},[snapshot.timestamp]);
  const m=snapshot.metrics||{},cpu=m.cpu||{},memory=m.memory||{},network=m.network||{},gpu=m.gpus?.[0];
  const processes=useMemo(()=>m.processes||[],[m.processes]);
  const openChangelog=()=>{fetch("/api/changelog").then(r=>r.json()).then(v=>setChange(v.markdown||"")).catch(()=>setChange("Changelog konnte nicht geladen werden."));setModal("changelog")};
  const saveToken=(value:string)=>{localStorage.setItem("ncc-token",value);setToken(value)};
  return <main className="shell"><header className="header"><div className="brand"><div className="brandmark"><Activity size={22}/></div><div><div className="eyebrow">Real-time control plane</div><h1 className="title">no0bz Command Center</h1></div></div><div className="actions"><div className="status"><span className={`dot ${connected?"live":""}`}/>{connected?"Live":"Offline"}</div><button className="button" onClick={openChangelog}><Database size={16}/>Changelog</button><button className="button" onClick={()=>setModal("settings")}><Settings size={16}/>Settings</button></div></header>
  <div className="grid"><Card title="CPU load" icon={<Cpu size={17}/>}><Gauge label="Processor" value={cpu.percent}/><div className="metric-row"><span className="muted">Frequency</span><span>{cpu.frequency_mhz||"—"} MHz</span></div></Card><Card title="Memory" icon={<Database size={17}/>}><Gauge label="Memory" value={memory.percent}/><div className="metric-row"><span className="muted">Used / Total</span><span>{memory.used_gb||"—"} / {memory.total_gb||"—"} GB</span></div></Card>{gpu&&<Card title="GPU" icon={<MonitorCog size={17}/>}><Gauge label={gpu.name||"GPU"} value={gpu.percent}/><div className="metric-row"><span className="muted">Temperature</span><span>{gpu.temperature_c||"—"} °C</span></div></Card>}<Card title="Storage" icon={<HardDrive size={17}/>}><div className="scroll">{(m.disks||[]).map((d:AnyMap)=><div className="metric-row" key={d.name+d.mount}><span>{d.name}</span><span>{d.percent}%</span></div>)}</div></Card><Card title="Network telemetry" icon={<Network size={17}/>} wide><NetworkGraph samples={samples}/><div className="metric-row"><span style={{color:"var(--accent)"}}>↓ {network.download_mbps||0} Mbps</span><span style={{color:"var(--accent2)"}}>↑ {network.upload_mbps||0} Mbps</span></div></Card><Card title="Connected nodes" icon={<Users size={17}/>} wide><div className="scroll">{nodes.map(n=><div className="metric-row" key={n.node_id}><span>{n.profile?.alias||n.name}</span><span className="status"><span className={`dot ${n.online?"live":""}`}/>{n.online?"online":"offline"}</span></div>)}</div></Card><Card title="Top processes" icon={<Activity size={17}/>} wide><div className="process muted"><span>Name</span><span>CPU</span><span>RAM</span></div><div className="scroll">{processes.slice(0,14).map((p:AnyMap)=><div className="process" key={p.pid}><span>{p.name}</span><span>{p.cpu}%</span><span>{p.memory}%</span></div>)}</div></Card><Card title="Local hub" icon={<MessageSquare size={17}/>} wide><div className="empty">Prompt-, Code- und Datei-Hub ist über die API verbunden.</div></Card></div>
  {modal&&<div className="modalback" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><div className="modal"><div className="cardhead"><h2>{modal==="settings"?"Settings":"Changelog"}</h2><button className="button" onClick={()=>setModal(null)} aria-label="Dialog schließen"><X size={17}/></button></div>{modal==="settings"?<div className="formgrid"><label>Theme<select value={theme} onChange={e=>setTheme(e.target.value)}>{THEMES.map(t=><option key={t[0]} value={t[0]}>{t[1]}</option>)}</select></label><label>NCC Token<input value={token} onChange={e=>saveToken(e.target.value)} type="password" placeholder="Token für LAN-Zugriff"/></label><p className="muted">Layout und Theme werden nur in diesem Browser gespeichert. Hardware-Kacheln erscheinen dynamisch.</p></div>:<pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",color:"var(--muted)"}}>{change}</pre>}</div></div>}{error&&<button className="toast" onClick={()=>setError("")}>{error}</button>}</main>
}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);

